//
// Generated file, do not edit! Created by nedtool 4.6 from IPoIBFrame.msg.
//

#ifndef _IPOIBFRAME_M_H_
#define _IPOIBFRAME_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>IPoIBFrame.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message IPoIBFrame
 * {
 *     int sLid;
 *     int dLid;
 *     int Pkey;
 *     int sl;
 *     int vl;
 *     int FrameType; // 0 => IPoIBARP; 1 => IPoIBDataFrame;
 * }
 * </pre>
 */
class IPoIBFrame : public ::cMessage
{
  protected:
    int sLid_var;
    int dLid_var;
    int Pkey_var;
    int sl_var;
    int vl_var;
    int FrameType_var;

  private:
    void copy(const IPoIBFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const IPoIBFrame&);

  public:
    IPoIBFrame(const char *name=NULL, int kind=0);
    IPoIBFrame(const IPoIBFrame& other);
    virtual ~IPoIBFrame();
    IPoIBFrame& operator=(const IPoIBFrame& other);
    virtual IPoIBFrame *dup() const {return new IPoIBFrame(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSLid() const;
    virtual void setSLid(int sLid);
    virtual int getDLid() const;
    virtual void setDLid(int dLid);
    virtual int getPkey() const;
    virtual void setPkey(int Pkey);
    virtual int getSl() const;
    virtual void setSl(int sl);
    virtual int getVl() const;
    virtual void setVl(int vl);
    virtual int getFrameType() const;
    virtual void setFrameType(int FrameType);
};

inline void doPacking(cCommBuffer *b, IPoIBFrame& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, IPoIBFrame& obj) {obj.parsimUnpack(b);}


#endif // ifndef _IPOIBFRAME_M_H_

