//
// Generated file, do not edit! Created by nedtool 4.6 from IPoIBFrameIB.msg.
//

#ifndef _IPOIBFRAMEIB_M_H_
#define _IPOIBFRAMEIB_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>IPoIBFrameIB.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet IPoIBFrameIB
 * {
 *     int sLid;
 *     int dLid;
 *     int Pkey;
 *     int sl;
 *     int vl;
 *     int FrameType; // 0 => IPoIBARP; 1 => IPoIBDataFrame;
 * }
 * </pre>
 */
class IPoIBFrameIB : public ::cPacket
{
  protected:
    int sLid_var;
    int dLid_var;
    int Pkey_var;
    int sl_var;
    int vl_var;
    int FrameType_var;

  private:
    void copy(const IPoIBFrameIB& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const IPoIBFrameIB&);

  public:
    IPoIBFrameIB(const char *name=NULL, int kind=0);
    IPoIBFrameIB(const IPoIBFrameIB& other);
    virtual ~IPoIBFrameIB();
    IPoIBFrameIB& operator=(const IPoIBFrameIB& other);
    virtual IPoIBFrameIB *dup() const {return new IPoIBFrameIB(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSLid() const;
    virtual void setSLid(int sLid);
    virtual int getDLid() const;
    virtual void setDLid(int dLid);
    virtual int getPkey() const;
    virtual void setPkey(int Pkey);
    virtual int getSl() const;
    virtual void setSl(int sl);
    virtual int getVl() const;
    virtual void setVl(int vl);
    virtual int getFrameType() const;
    virtual void setFrameType(int FrameType);
};

inline void doPacking(cCommBuffer *b, IPoIBFrameIB& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, IPoIBFrameIB& obj) {obj.parsimUnpack(b);}


#endif // ifndef _IPOIBFRAMEIB_M_H_

