//
// Generated file, do not edit! Created by nedtool 4.6 from QPsendCompletion.msg.
//

#ifndef _QPSENDCOMPLETION_M_H_
#define _QPSENDCOMPLETION_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>QPsendCompletion.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message QPsendCompletion
 * {
 *     bool sendSuccessStat;
 * }
 * </pre>
 */
class QPsendCompletion : public ::cMessage
{
  protected:
    bool sendSuccessStat_var;

  private:
    void copy(const QPsendCompletion& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const QPsendCompletion&);

  public:
    QPsendCompletion(const char *name=NULL, int kind=0);
    QPsendCompletion(const QPsendCompletion& other);
    virtual ~QPsendCompletion();
    QPsendCompletion& operator=(const QPsendCompletion& other);
    virtual QPsendCompletion *dup() const {return new QPsendCompletion(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual bool getSendSuccessStat() const;
    virtual void setSendSuccessStat(bool sendSuccessStat);
};

inline void doPacking(cCommBuffer *b, QPsendCompletion& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, QPsendCompletion& obj) {obj.parsimUnpack(b);}


#endif // ifndef _QPSENDCOMPLETION_M_H_

